#!/bin/bash

# set -x
trap "exit" INT

OPTION="-checksafety -debug"
MAXJOBS="3"

declare -A SUBDIRS

# Examples, sct-preserv
SUBDIRS[sct-examples/chacha20/avx2/chacha20_v1.jazz]="plain;len"
SUBDIRS[sct-examples/chacha20/avx2/chacha20_v4.jazz]="plain;len"
SUBDIRS[sct-examples/chacha20/ref/chacha20.jazz]="plain;len"
SUBDIRS[sct-examples/chacha20/ref/chacha20_v1.jazz]="plain;len"
SUBDIRS[sct-examples/chacha20/ref/chacha20_v4_weak.jazz]="plain;len"
SUBDIRS[sct-examples/chacha20/ref/chacha20_v4.jazz]="plain;len"
# SUBDIRS[sct-examples/chacha20/avx2/chacha20_v1.jazz]="output;len|plain;len"
# SUBDIRS[sct-examples/chacha20/avx2/chacha20_v4.jazz]="output;len|plain;len"
# SUBDIRS[sct-examples/chacha20/ref/chacha20.jazz]="output;len|plain;len"
# SUBDIRS[sct-examples/chacha20/ref/chacha20_v1.jazz]="output;len|plain;len"
# SUBDIRS[sct-examples/chacha20/ref/chacha20_v4_weak.jazz]="output;len|plain;len"
# SUBDIRS[sct-examples/chacha20/ref/chacha20_v4.jazz]="output;len|plain;len"
SUBDIRS[sct-examples/poly1305/avx2/poly1305.japp]="in;inlen"
SUBDIRS[sct-examples/poly1305/avx2/poly1305_v4.japp]="in;inlen"
SUBDIRS[sct-examples/poly1305/avx2/poly1305_export_v4.japp]="in;inlen"
SUBDIRS[sct-examples/poly1305/avx2/poly1305_export.japp]="in;inlen"
SUBDIRS[sct-examples/curve25519/ref4/curve25519.japp]=";"
SUBDIRS[sct-examples/curve25519/ref4/curve25519_v4.japp]=";"


CURJOBS=0
for i in "${!SUBDIRS[@]}"; do
  # If true, wait until the next background job finishes to continue.
  ((cur_jobs >= MAXJOBS)) && wait -n
  echo "Starting ${i}"
  (../jasminc ${OPTION} -safetyparam ${SUBDIRS[$i]} ${i} &> ${i}.res ;
   echo "=> Done ${i}, results" ;
   grep Safety ${i}/out.res | sed 's/^/  /'
  ) & ((++cur_jobs))
done

wait
