#!/bin/bash

# set -x
trap "exit" INT

OPTION="-checksafety -debug"
MAXJOBS="3"

declare -A SUBDIRS

# libjc, master
SUBDIRS[crypto_onetimeauth/poly1305/ref3/in.japp]="in;inlen"
SUBDIRS[crypto_onetimeauth/poly1305/avx/in.japp]="in;inlen"
SUBDIRS[crypto_onetimeauth/poly1305/avx2/in.japp]="in;inlen"
SUBDIRS[crypto_stream/chacha20/ref/in.japp]="plain;len"
SUBDIRS[crypto_stream/chacha20/avx/in.japp]="plain;len"
SUBDIRS[crypto_stream/chacha20/avx2/in.japp]="plain;len"
# SUBDIRS[crypto_stream/chacha20/ref/in.japp]="output;len|plain;len"
# SUBDIRS[crypto_stream/chacha20/avx/in.japp]="output;len|plain;len"
# SUBDIRS[crypto_stream/chacha20/avx2/in.japp]="output;len|plain;len"
SUBDIRS[crypto_scalarmult/curve25519/ref4/in.japp]=";"
SUBDIRS[crypto_scalarmult/curve25519/mulx/in.japp]=";"


CURJOBS=0
for i in "${!SUBDIRS[@]}"; do
  # If true, wait until the next background job finishes to continue.
  ((cur_jobs >= MAXJOBS)) && wait -n
  echo "Starting ${i}"
  (../jasminc ${OPTION} -safetyparam ${SUBDIRS[$i]} ${i} &> ${i}.res ;
   echo "=> Done ${i}, results" ;
   grep Safety ${i}/out.res | sed 's/^/  /'
  ) & ((++cur_jobs))
done

wait
